const Types = {
	GET_MOVIES: "GET_MOVIES",
	FILTER_BY_NAME: "FILTER_BY_NAME",
	HANDLE_SEARCH_MOVIES: "HANDLE_SEARCH_MOVIES",
	IS_LOANDING_MOVIES: "IS_LOANDING_MOVIES",
	GET_MOVIES_SUCESS: "GET_MOVIES_SUCESS",
	GET_MOVIES_IS_LOADING: "GET_MOVIES_IS_LOADING",
	GET_MOVIES_FAILURE: "GET_MOVIES_FAILURE",
	LIKE_MOVIE: "LIKE_MOVIE",
	ORDER_MOVIES: "ORDER_MOVIES",
	ADD_MOVIE: "ADD_MOVIE"
}

export default Types;